from enum import Enum


class CorporateActionTypeEnum(str, Enum):
    """Types of corporate actions"""
    # Cash distributions
    DIVIDEND = "DIVIDEND"
    SPECIAL_DIVIDEND = "SPECIAL_DIVIDEND"
    DISTRIBUTION = "DISTRIBUTION"
    RETURN_OF_CAPITAL = "RETURN_OF_CAPITAL"

    # Stock changes
    STOCK_SPLIT = "STOCK_SPLIT"
    STOCK_DIVIDEND = "STOCK_DIVIDEND"
    REVERSE_SPLIT = "REVERSE_SPLIT"
    SPIN_OFF = "SPIN_OFF"

    # Corporate restructuring
    MERGER = "MERGER"
    ACQUISITION = "ACQUISITION"
    TENDER_OFFER = "TENDER_OFFER"
    EXCHANGE_OFFER = "EXCHANGE_OFFER"

    # Rights and warrants
    RIGHTS_ISSUE = "RIGHTS_ISSUE"
    WARRANT_EXERCISE = "WARRANT_EXERCISE"
    SUBSCRIPTION = "SUBSCRIPTION"

    # Symbol changes
    IDENTIFIER_CHANGE = "IDENTIFIER_CHANGE"

    # Delistings and reorganizations
    DELISTING = "DELISTING"
    BANKRUPTCY = "BANKRUPTCY"
    LIQUIDATION = "LIQUIDATION"
    REORGANIZATION = "REORGANIZATION"

    # Other
    BONUS_ISSUE = "BONUS_ISSUE"
    CONVERSION = "CONVERSION"
    REDEMPTION = "REDEMPTION"
    MATURITY = "MATURITY"
    CALL = "CALL"
    PUT = "PUT"
