from enum import Enum


class PortfolioTypeEnum(str, Enum):
    """Types of portfolios based on structure and regulatory framework"""
    MUTUAL_FUND = "MUTUAL_FUND"
    ETF = "ETF"  # Exchange Traded Fund
    HEDGE_FUND = "HEDGE_FUND"
    PENSION_FUND = "PENSION_FUND"
    SOVEREIGN_WEALTH_FUND = "SOVEREIGN_WEALTH_FUND"
    PRIVATE_EQUITY = "PRIVATE_EQUITY"
    VENTURE_CAPITAL = "VENTURE_CAPITAL"
    REAL_ESTATE_FUND = "REAL_ESTATE_FUND"
    COMMODITY_FUND = "COMMODITY_FUND"
    BALANCED_FUND = "BALANCED_FUND"
    INDEX_FUND = "INDEX_FUND"
    ACTIVELY_MANAGED = "ACTIVELY_MANAGED"
    QUANTITATIVE = "QUANTITATIVE"
    MULTI_ASSET = "MULTI_ASSET"
    SECTOR_SPECIFIC = "SECTOR_SPECIFIC"
    GEOGRAPHIC_SPECIFIC = "GEOGRAPHIC_SPECIFIC"
    INCOME_FOCUSED = "INCOME_FOCUSED"
    GROWTH_FOCUSED = "GROWTH_FOCUSED"
    VALUE_FOCUSED = "VALUE_FOCUSED"
    CUSTOM = "CUSTOM"
