from enum import Enum


class WeightingMethodologyEnum(Enum):
    PRICE_WEIGHTED = "PRICE_WEIGHTED"
    MARKET_CAP_WEIGHTED = "MARKET_CAP_WEIGHTED"
    EQUALLY_WEIGHTED = "EQUALLY_WEIGHTED"
    FIXED_WEIGHTED = "FIXED_WEIGHTED"
