from enum import Enum


class CorporateActionTypeEnum(str, Enum):
    # Mandatory Corporate Actions
    CASH_DIVIDEND = "CASH_DIVIDEND"
    STOCK_DIVIDEND = "STOCK_DIVIDEND"
    SPECIAL_DIVIDEND = "SPECIAL_DIVIDEND"
    STOCK_SPLIT = "STOCK_SPLIT"
    RIGHTS_ISSUE = "RIGHTS_ISSUE"

    MERGER = "MERGER"
    ACQUISITION = "ACQUISITION"
    TAKEOVER = "TAKEOVER"
    AMALGAMATION = "AMALGAMATION"
    SPIN_OFF = "SPIN_OFF"
    CAPITAL_REDUCTION = "CAPITAL_REDUCTION"

    DELISTING = "DELISTING"

    # Voluntary Corporate Actions
    SHARE_BUYBACK = "SHARE_BUYBACK"
    TENDER_OFFER = "TENDER_OFFER"
    RIGHTS_ISSUE_OPTIONAL = "RIGHTS_ISSUE_OPTIONAL"
    WARRANT_EXERCISE = "WARRANT_EXERCISE"
    EXCHANGE_OFFER = "EXCHANGE_OFFER"

    # Mandatory with Choice Corporate Actions
    DIVIDEND_OPTION = "DIVIDEND_OPTION"
    PARTIAL_BUYBACK = "PARTIAL_BUYBACK"
